server:
  port: 9903

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/

spring:
  application:
    name: api
  cloud:
    loadbalancer:
      retry:
        enabled: false
#server： 随便起   path： 前缀   serviceId：服务名（application.name）
zuul:
  routes:
    server:
      path: /server/**
      serviceId: provide-service
      sensitiveHeaders: "*"
    web:
      path: /web/**
      serviceId: web-service
      sensitiveHeaders: "*"